### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Azizmkadmini** [notakamihe/ECommerce-Angular-Spring#1]
failed build ???? angular 
Error: ./src/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\postcss\package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\css-loader\dist\index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\Compilation.js:739:10)
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\Compilation.js:1111:12
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModuleFactory.js:409:6
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModuleFactory.js:138:29
    at C:\Users\mkadm\OneDrive\Bureau\angular\frontend\node_modules\webpack\lib\NormalModuleFactory.js:346:9

**Comment by ErAnuragChaturvedi** [comment]
Cannot find module '@angular/compiler/src/util' or its corresponding type declarations.

1 import { Byte } from '@angular/compiler/src/util';


 Cannot find module '@fortawesome/free-solid-svg-icons' or its corresponding type 
declarations.

3 import { faCaretUp, faCaretDown } from "@fortawesome/free-solid-svg-icons";
facing these kind of issues during working on it 
please if u face the same that time then suggest me what can i do now ....
